export { default as HeroSection } from './HeroSection'
export { default as AboutSection } from './AboutSection'
export { default as SkillsSection } from './SkillsSection'
export { default as ExperienceSection } from './ExperienceSection'
export { default as ProjectsSection } from './ProjectsSection'
export { default as CertificationsSection } from './CertificationsSection'
export { default as ProfilesSection } from './ProfilesSection'
export { default as ContactSection } from './ContactSection'
